runtime: python
env: flex
runtime_config:
        python_version: 3
env_variables:
        CLOUD_STORAGE_BUCKET: hannah-galbraith
        PROJECT_ID: hannah-galbraith
entrypoint: gunicorn -b :$PORT app:app
